lava_dispatcher: lava_test_shell: distro: update os build and pkg manager scripts

diff --git a/lava_dispatcher/lava_test_shell/distro/fedora/lava-install-packages b/lava_dispatcher/lava_test_shell/distro/fedora/lava-install-packages
--- a/lava_dispatcher/lava_test_shell/distro/fedora/lava-install-packages
+++ b/lava_dispatcher/lava_test_shell/distro/fedora/lava-install-packages
@@ -1,18 +1,20 @@
 #!/bin/sh
-retry=0
-max_retry=4
 
-while [ 1 ]
+retry=1
+max_retry=3
+
+while true
 do
-  dnf -y upgrade --refresh 
-  dnf -y install "$@"
-  return_value=$?
-  [ "$return_value" = 0 ] && break
-  [ "$retry" = "$max_retry" ] && exit $return_value
+    dnf -y upgrade --refresh
+    dnf -y install "$@"
+    return_value=$?
+    [ $return_value -eq 0 ] && break
+    [ $retry -eq $max_retry ] && exit $return_value
 
-  echo "================================================="
-  echo "($retry) Install failed... Retrying after some seconds"
-  echo "================================================="
-  sleep 60
-  retry=$((retry+1))
+    echo "================================================="
+    echo "($retry) Install failed... Retrying after some seconds"
+    echo "================================================="
+
+    sleep 20
+    retry=$((retry+1))
 done
diff --git a/lava_dispatcher/lava_test_shell/distro/oe/lava-install-packages b/lava_dispatcher/lava_test_shell/distro/oe/lava-install-packages
--- a/lava_dispatcher/lava_test_shell/distro/oe/lava-install-packages
+++ b/lava_dispatcher/lava_test_shell/distro/oe/lava-install-packages
@@ -3,28 +3,29 @@
 #set proxy in /etc/opkg/opkg.conf if required
 unset http_proxy
 
-retry=0
-max_retry=4
+retry=1
+max_retry=3
 
 which opkg
 rc=$?
 
-if [ "$rc" != 0 ]; then
-  echo "Error: OPKG package manager not found in the path."
-  exit $rc
+if [ $rc -ne 0 ]; then
+    echo "Error: OPKG package manager not found in the path."
+    exit $rc
 fi
 
-while [ 1 ]
+while true
 do
-  opkg update
-  opkg install "$@"
-  return_value=$?
-  [ "$return_value" = 0 ] && break
-  [ "$retry" = "$max_retry" ] && exit $return_value
+    opkg update
+    opkg install "$@"
+    return_value=$?
+    [ $return_value -eq 0 ] && break
+    [ $retry -eq $max_retry ] && exit $return_value
 
-  echo "================================================="
-  echo "($retry) Install failed... Retrying after some seconds"
-  echo "================================================="
-  sleep 60
-  retry=$((retry+1))
+    echo "================================================="
+    echo "($retry) Install failed... Retrying after some seconds"
+    echo "================================================="
+
+    sleep 20
+    retry=$((retry+1))
 done
diff --git a/lava_dispatcher/lava_test_shell/distro/opensuse/lava-install-packages b/lava_dispatcher/lava_test_shell/distro/opensuse/lava-install-packages
--- a/lava_dispatcher/lava_test_shell/distro/opensuse/lava-install-packages
+++ b/lava_dispatcher/lava_test_shell/distro/opensuse/lava-install-packages
@@ -1,20 +1,20 @@
 #!/bin/bash
 
-retry=0
+retry=1
 max_retry=3
 
-while [ 1 ] 
+while true
 do
-    zypper -n update 
+    zypper -n update
     zypper -q install -f "$@"
     return_vale=$?
-    [ "$return_value" -eq 0 ] && break
-    [ "$retry" -eq "$max_retry" ] && exit $return_value
+    [ $return_value -eq 0 ] && break
+    [ $retry -eq $max_retry ] && exit $return_value
 
     echo "================================================="
-    echo "$retry  Install failed... Retrying after some seconds"
+    echo "($retry) Install failed... Retrying after some seconds"
     echo "================================================="
 
-    sleep 60
+    sleep 20
     retry=$((retry+1))
 done
diff --git a/lava_dispatcher/lava_test_shell/distro/ubuntu/lava-install-packages b/lava_dispatcher/lava_test_shell/distro/ubuntu/lava-install-packages
--- a/lava_dispatcher/lava_test_shell/distro/ubuntu/lava-install-packages
+++ b/lava_dispatcher/lava_test_shell/distro/ubuntu/lava-install-packages
@@ -1,19 +1,20 @@
 #!/bin/sh
 
-retry=0
-max_retry=4
+retry=1
+max_retry=3
 
-while [ 1 ]
+while true
 do
-  DEBIAN_FRONTEND=noninteractive apt-get update
-  DEBIAN_FRONTEND=noninteractive apt-get install -y -q "$@"
-  return_value=$?
-  [ "$return_value" = 0 ] && break
-  [ "$retry" = "$max_retry" ] && exit $return_value
+    DEBIAN_FRONTEND=noninteractive apt-get update
+    DEBIAN_FRONTEND=noninteractive apt-get install -y -q "$@"
+    return_value=$?
+    [ $return_value -eq 0 ] && break
+    [ $retry -eq $max_retry ] && exit $return_value
 
-  echo "================================================="
-  echo "($retry) Install failed... Retrying after some seconds"
-  echo "================================================="
-  sleep 60
-  retry=$((retry+1))
+    echo "================================================="
+    echo "($retry) Install failed... Retrying after some seconds"
+    echo "================================================="
+
+    sleep 20
+    retry=$((retry+1))
 done
